allowBuilds:
  core-js: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - postcss@8.5.10
minimumReleaseAgeStrict: true
overrides:
  html2canvas: npm:html2canvas-pro@2.0.2
  postcss@<8.5.10: ^8.5.10
